version: '3'

volumes:
  static:
  database:

services:
  blogproject:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: blogproject
    container_name: blogproject
    working_dir: /app
    volumes:
      - database:/app/database
      - static:/app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: blog_nginx
    container_name: blog_nginx
    volumes:
      - static:/apps/gqp/blogproject/static
    ports:
      - "80:80"
      - "443:443"
